# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Player-Musicus
version:      1.32
version_from: lib/POE/Component/Player/Musicus.pm
installdirs:  site
requires:
    POE::Component::Child:         1.39
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
